### ISSUE TITLE
run on custom video

### ISSUE THREAD

**Issue by setarekhosravi** [SparkTempest/Bi-directional-Adapter#5]
I want to run your tracker on custom video, but I see this error after selecting the area I want to track.
`
Traceback (most recent call last):
  File "/media/strh/MyDrive/Track/OtherTracking/BAT/tracking/video_demo.py", line 44, in <module>
    main()
  File "/media/strh/MyDrive/Track/OtherTracking/BAT/tracking/video_demo.py", line 40, in main
    run_video(args.tracker_name, args.tracker_param, args.videofile, args.optional_box, args.debug, args.save_results)
  File "/media/strh/MyDrive/Track/OtherTracking/BAT/tracking/video_demo.py", line 20, in run_video
    tracker.run_video(videofilepath=videofile, optional_box=optional_box, debug=debug, save_results=save_results)
  File "/media/strh/MyDrive/Track/OtherTracking/BAT/tracking/../lib/test/evaluation/tracker.py", line 226, in run_video
    tracker.initialize(frame, _build_init_info(init_state))
  File "/media/strh/MyDrive/Track/OtherTracking/BAT/tracking/../lib/test/tracker/bat.py", line 47, in initialize
    template = self.preprocessor.process(z_patch_arr)
  File "/media/strh/MyDrive/Track/OtherTracking/BAT/tracking/../lib/test/tracker/data_utils.py", line 23, in process
    img_tensor_norm = ((img_tensor / 255.0) - self.mean) / self.std  # (1,6,H,W)
RuntimeError: The size of tensor a (3) must match the size of tensor b (6) at non-singleton dimension 1
`

**Comment by setarekhosravi** [comment]
I used `video_demo.py` looklike OSTrack.

**Comment by SparkTempest** [comment]
> I want to run your tracker on custom video, but I see this error after selecting the area I want to track. `Traceback (most recent call last): File "/media/strh/MyDrive/Track/OtherTracking/BAT/tracking/video_demo.py", line 44, in <module> main() File "/media/strh/MyDrive/Track/OtherTracking/BAT/tracking/video_demo.py", line 40, in main run_video(args.tracker_name, args.tracker_param, args.videofile, args.optional_box, args.debug, args.save_results) File "/media/strh/MyDrive/Track/OtherTracking/BAT/tracking/video_demo.py", line 20, in run_video tracker.run_video(videofilepath=videofile, optional_box=optional_box, debug=debug, save_results=save_results) File "/media/strh/MyDrive/Track/OtherTracking/BAT/tracking/../lib/test/evaluation/tracker.py", line 226, in run_video tracker.initialize(frame, _build_init_info(init_state)) File "/media/strh/MyDrive/Track/OtherTracking/BAT/tracking/../lib/test/tracker/bat.py", line 47, in initialize template = self.preprocessor.process(z_patch_arr) File "/media/strh/MyDrive/Track/OtherTracking/BAT/tracking/../lib/test/tracker/data_utils.py", line 23, in process img_tensor_norm = ((img_tensor / 255.0) - self.mean) / self.std # (1,6,H,W) RuntimeError: The size of tensor a (3) must match the size of tensor b (6) at non-singleton dimension 1`

Are you tracking RGBT/E or other multimodal data videos? OSTrack is designed for single-modal data. For BAT, you need to provide template frames and video frame sequences for two modalities. In the code, these two modal images are concatenated together before being fed into the network and then separated before processing. If you only have single-modal data, you may encounter an error like 'in process img_tensor_norm = ((img_tensor / 255.0) - self.mean) / self.std # (1,6,H,W) RuntimeError: The size of tensor a (3) must match the size of tensor b (6) at non-singleton dimension 1'.

**Comment by setarekhosravi** [comment]
Thank you.
Is there another way to run your model on custom single-modal data? (For example just an IR video)
